### ISSUE TITLE
Aplicar assets para todas as paginas principais.

### ISSUE THREAD

**Issue by atmosmaciel** [soluises/portal-soluises#4]
Todas as páginas principais foram colocadas dentro da pasta views. É preciso aplicar os assets nelas também somente a index é com os assets aplicados.

**Comment by lucassouzavieira** [comment]
@atmosmaciel Let's code

**Comment by lucassouzavieira** [comment]
@atmosmaciel, sobre essa issue, não seria melhor configurar as tarefas de front-end no mix antes de resolver ela ?

**Comment by atmosmaciel** [comment]
Verdade, melhor mesmo. Eu não sei como fazer isso no mix. Mas su pide ir adiantando melhor. Valeu!
